[package]
name = "osm4routing"
version = "0.1.0"
authors = ["Tristram Gr√§bener <tristramg@gmail.com>"]
description = "Convert OpenStreetMap data into routing friendly CSV"
homepage = "https://github.com/Tristramg/osm4routing2"
readme = "readme.md"
license = "MIT"
license-file = "LICENCE.md"

[dependencies]
osmpbfreader = "0.3"
csv = "0.14.7"

[lib]
name = "osm4routing"
path = "src/osm4routing/mod.rs"
