[package]
name = "osm4routing"
edition = "2021"
version = "0.5.4"
authors = ["Tristram Gr√§bener <tristramg@gmail.com>"]
description = "Convert OpenStreetMap data into routing friendly CSV"
homepage = "https://github.com/Tristramg/osm4routing2"
readme = "readme.md"
license = "MIT"

[dependencies]
osmpbfreader = "0.16.0"
csv = "1.1.3"
docopt = "1.1.0"
serde = "1.0"
serde_json = "1.0.97"

[lib]
name = "osm4routing"
