[package]
name = "osm4routing"
edition = "2021"
version = "0.5.9"
authors = ["Tristram Gr√§bener <tristramg@gmail.com>"]
description = "Convert OpenStreetMap data into routing friendly CSV"
homepage = "https://github.com/Tristramg/osm4routing2"
readme = "readme.md"
license = "MIT"

[dependencies]
osmpbfreader = "0.16.1"
csv = "1.3.0"
docopt = "1.1.1"
serde = "1.0"

[lib]
name = "osm4routing"
