[package]
name = "osm4routing2"
version = "0.1.0"
authors = ["Tristram Gr√§bener <tristramg@gmail.com>"]

[dependencies]
osmpbfreader = "0.3"
csv = "0.14.7"

[lib]
name = "osm4routing"
path = "src/osm4routing/mod.rs"
